### ISSUE TITLE
Feature request: add a comparison between gpack and other managers like use-package, leaf etc.

### ISSUE THREAD

**Issue by QiangF** [SpringHan/package-require#2]

**Comment by SpringHan** [comment]
The functions of `gpack` are less than the other package managers, and the main functions don't need to compair. All the functions are listed in the README. So sorry, I won't add any comparison.  
You may ask: "So why did you write gpack?". I can reply you, the predecessor of `gpack` is the first function that I wrote, so It's a memory of the times that I learn Emacs.
